In [1]:
import numpy as np

In [4]:
a=np.array([1,2,3])
print(a)

[1 2 3]


In [7]:
b=np.arange(0,10,3)
print(b)

[0 3 6 9]


In [8]:
d=np.zeros((2,3))
print(d)

[[0. 0. 0.]
 [0. 0. 0.]]


In [10]:
d=np.zeros((2,3),dtype=int)
print(d)

[[0 0 0]
 [0 0 0]]


In [13]:
e=np.ones((3,2))
print(e)

[[1. 1.]
 [1. 1.]
 [1. 1.]]


In [15]:
f=np.eye(4)
print(f)

[[1. 0. 0. 0.]
 [0. 1. 0. 0.]
 [0. 0. 1. 0.]
 [0. 0. 0. 1.]]


In [16]:
a1=np.array([1,2,3])

In [17]:
a2=np.array([1,2])
b2=np.array([3,4])
stacked=np.vstack([a2,b2])
print("stacked array:\n",stacked)

stacked array:
 [[1 2]
 [3 4]]


In [18]:
a2=np.array([1,2])
b2=np.array([3,4])
stacked=np.hstack([a2,b2])
print("stacked array:\n",stacked)

stacked array:
 [1 2 3 4]


In [19]:
# math opertation numpy

In [21]:
g=np.array([1,2,3,4])
added=np.add(g,2)
print("Added 2 to g ",added)

Added 2 to g  [3 4 5 6]


In [23]:
g=np.array([1,2,3,4])
sqrt=np.power(g,2)
print("squre g ",sqrt)

squre 2 to g  [ 1  4  9 16]


In [24]:
g=np.array([1,2,3,4])
sqrt=np.sqrt(g)
print("squre 2 to g ",sqrt)

squre 2 to g  [1.         1.41421356 1.73205081 2.        ]


In [25]:
print(a)
print(g)

[1 2 3]
[1 2 3 4]


In [26]:
a3=np.array([1,2,3])
dot_product=np.dot(a,g)
print(dot_product)

ValueError: shapes (3,) and (4,) not aligned: 3 (dim 0) != 4 (dim 0)

In [28]:
print(a)
print(a1)

[1 2 3]
[1 2 3]


In [39]:
a3=np.array([1,2,3,4])
dot_product=np.dot(a1,a)
print("dot product of a1 and a",dot_product)

dot product of a1 and a 14


In [32]:
# Stat

In [40]:
s=np.array([1,2,3,4])
mean=np.mean(s)
print("Mean of s:",mean)

Mean of s: 2.5


In [41]:
var =np.var(s)
print("Variance of s:",var)

Variance of s: 1.25


In [42]:
#Standerd derivation of an array
std_dev =np.std(s)
print("Standerd derivation of s:",std_dev)

Standerd derivation of s: 1.118033988749895


In [44]:
min=np.min(s)
max=np.max(s)

print(min)
print(max)

1
4


# Linear Algebera Funcations

# Randaom Sampleinng function

In [45]:
random_vals=np.random.rand(3)
print("Random values:", random_vals)

Random values: [0.53174848 0.93353249 0.31768314]


In [69]:
np.random.seed()
rand_ints=np.random.randint(0,10,size=4)
print("Random intenger:", rand_ints)

Random intenger: [4 5 0 4]
