In [1]:
import numpy as np

In [4]:
np.__version__

'2.4.6'

In [5]:
import sys

In [6]:
sys.version

'3.14.6 | packaged by Anaconda, Inc. | (main, Jul  9 2026, 14:29:05) [MSC v.1942 64 bit (AMD64)]'

In [8]:
# Create a list

my_list=[0,1,2,3,4,5]
my_list

[0, 1, 2, 3, 4, 5]

In [9]:
type(my_list)

list

In [11]:
# Convert list to array

arr=np.array(my_list)
arr

array([0, 1, 2, 3, 4, 5])

In [14]:
print(type(arr))
print(type(my_list))

<class 'numpy.ndarray'>
<class 'list'>


In [16]:
    np.arange(5)

array([0, 1, 2, 3, 4])

In [18]:
np.arange(5,10)

array([5, 6, 7, 8, 9])

In [19]:
np.arange(5,100,10)

array([ 5, 15, 25, 35, 45, 55, 65, 75, 85, 95])

In [20]:
np.arange(20,10)

array([], dtype=int64)

In [21]:
np.arange(-20,10)

array([-20, -19, -18, -17, -16, -15, -14, -13, -12, -11, -10,  -9,  -8,
        -7,  -6,  -5,  -4,  -3,  -2,  -1,   0,   1,   2,   3,   4,   5,
         6,   7,   8,   9])

In [23]:
np.zeros(5)

array([0., 0., 0., 0., 0.])

In [24]:
np.zeros(5,dtype=int)

array([0, 0, 0, 0, 0])

In [26]:
np.zeros((2,2))

array([[0., 0.],
       [0., 0.]])

In [27]:
np.zeros((2,3),dtype=int)

array([[0, 0, 0],
       [0, 0, 0]])

In [29]:
np.zeros((10,10),dtype=int)

array([[0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0]])

In [31]:
np.ones(4)

array([1., 1., 1., 1.])

In [33]:
np.ones((2,3),dtype=int)

array([[1, 1, 1],
       [1, 1, 1]])

In [35]:
np.two((2,3))

AttributeError: module 'numpy' has no attribute 'two'

In [36]:
np.three((2,3))

AttributeError: module 'numpy' has no attribute 'three'

In [37]:
rand(2,3)

NameError: name 'rand' is not defined

In [38]:
random.rand(2,3)


NameError: name 'random' is not defined

In [45]:
np.random.rand(2)

array([0.29957816, 0.16350207])

In [47]:
np.random.rand(2,3)

array([[0.03687295, 0.53454154, 0.34246113],
       [0.01258388, 0.23728657, 0.07516126]])

In [53]:
np.random.randint(2)

1

In [61]:
np.random.randint(2,9)

6

In [125]:
np.random.randint(2,9,4) # generate 

array([5, 4, 7, 3], dtype=int32)

In [124]:
import numpy as np

otp = np.random.randint(0, 10, 4)
print("Your OTP is:", ''.join(map(str, otp)))


Your OTP is: 6322


In [66]:
np.random.randint(10,40,(10,10))
# 10* 10 metrix betwwn 10 to 40

array([[28, 20, 20, 35, 18, 26, 33, 11, 34, 15],
       [19, 16, 10, 33, 34, 12, 24, 28, 18, 11],
       [35, 21, 15, 15, 12, 14, 28, 35, 24, 35],
       [20, 24, 10, 16, 14, 16, 20, 28, 11, 18],
       [16, 18, 10, 35, 37, 10, 38, 12, 14, 26],
       [33, 10, 26, 25, 30, 39, 18, 30, 27, 27],
       [33, 17, 23, 28, 37, 10, 23, 17, 39, 15],
       [21, 18, 18, 14, 28, 18, 19, 39, 34, 16],
       [30, 20, 29, 11, 34, 21, 39, 27, 14, 38],
       [21, 20, 19, 29, 31, 11, 38, 19, 33, 36]], dtype=int32)

In [68]:
arr1=np.random.randint(10,40,(10,10))
print(arr1)

[[17 38 30 34 24 14 35 27 37 36]
 [17 14 32 36 11 13 22 35 36 21]
 [39 20 28 38 19 15 12 13 15 19]
 [11 13 26 18 24 31 37 32 14 30]
 [16 28 18 30 39 26 12 14 35 14]
 [17 34 37 36 10 16 33 10 31 35]
 [16 28 10 24 22 17 12 17 11 20]
 [36 36 17 32 27 19 23 28 36 35]
 [12 34 31 31 38 27 19 24 28 38]
 [11 34 32 19 21 22 21 22 28 29]]


In [69]:
arr1[2]

array([39, 20, 28, 38, 19, 15, 12, 13, 15, 19], dtype=int32)

In [70]:
arr1[-2]

array([12, 34, 31, 31, 38, 27, 19, 24, 28, 38], dtype=int32)

In [71]:
arr1[5]

array([17, 34, 37, 36, 10, 16, 33, 10, 31, 35], dtype=int32)

In [73]:
b

[[3 7 4 3 3 8 5]
 [3 5 6 6 5 6 5]
 [5 2 8 2 5 4 4]
 [7 7 3 7 5 3 3]
 [8 3 3 5 5 8 2]]


In [74]:
arr2[3]

array([7, 7, 3, 7, 5, 3, 3], dtype=int32)

In [75]:
arr2[-3]

array([5, 2, 8, 2, 5, 4, 4], dtype=int32)

In [76]:
arr2

array([[3, 7, 4, 3, 3, 8, 5],
       [3, 5, 6, 6, 5, 6, 5],
       [5, 2, 8, 2, 5, 4, 4],
       [7, 7, 3, 7, 5, 3, 3],
       [8, 3, 3, 5, 5, 8, 2]], dtype=int32)

In [77]:
arr2[2,3]=10

In [78]:
arr2

array([[ 3,  7,  4,  3,  3,  8,  5],
       [ 3,  5,  6,  6,  5,  6,  5],
       [ 5,  2,  8, 10,  5,  4,  4],
       [ 7,  7,  3,  7,  5,  3,  3],
       [ 8,  3,  3,  5,  5,  8,  2]], dtype=int32)

In [79]:
arr2b

array([[ 3,  7,  4,  3,  3,  8,  5],
       [ 3,  5,  6,  6,  5,  6,  5],
       [ 5,  2,  8, 10,  5,  4,  4],
       [ 7,  7,  3,  7,  5,  3,  3],
       [ 8,  3,  3,  5,  5,  8,  2]], dtype=int32)

In [80]:
arr2[:2,0]

array([3, 3], dtype=int32)

In [82]:
arr2[:,-1]

array([5, 5, 4, 3, 2], dtype=int32)

In [83]:
arr2[2:5,2:5]

array([[ 8, 10,  5],
       [ 3,  7,  5],
       [ 3,  5,  5]], dtype=int32)

In [84]:
arr2

array([[ 3,  7,  4,  3,  3,  8,  5],
       [ 3,  5,  6,  6,  5,  6,  5],
       [ 5,  2,  8, 10,  5,  4,  4],
       [ 7,  7,  3,  7,  5,  3,  3],
       [ 8,  3,  3,  5,  5,  8,  2]], dtype=int32)

In [85]:
arr2[2:5,2:5]

array([[ 8, 10,  5],
       [ 3,  7,  5],
       [ 3,  5,  5]], dtype=int32)

In [86]:
#masking or fliter in numpy

In [87]:
arr2

array([[ 3,  7,  4,  3,  3,  8,  5],
       [ 3,  5,  6,  6,  5,  6,  5],
       [ 5,  2,  8, 10,  5,  4,  4],
       [ 7,  7,  3,  7,  5,  3,  3],
       [ 8,  3,  3,  5,  5,  8,  2]], dtype=int32)

In [88]:
arr2>5

array([[False,  True, False, False, False,  True, False],
       [False, False,  True,  True, False,  True, False],
       [False, False,  True,  True, False, False, False],
       [ True,  True, False,  True, False, False, False],
       [ True, False, False, False, False,  True, False]])

In [89]:
arr2[arr2>5]

array([ 7,  8,  6,  6,  6,  8, 10,  7,  7,  7,  8,  8], dtype=int32)

In [90]:
arr2[arr2>=5]

array([ 7,  8,  5,  5,  6,  6,  5,  6,  5,  5,  8, 10,  5,  7,  7,  7,  5,
        8,  5,  5,  8], dtype=int32)

In [91]:
arr2[arr2==5]

array([5, 5, 5, 5, 5, 5, 5, 5, 5], dtype=int32)

In [92]:
arr2[arr2!=5]

array([ 3,  7,  4,  3,  3,  8,  3,  6,  6,  6,  2,  8, 10,  4,  4,  7,  7,
        3,  7,  3,  3,  8,  3,  3,  8,  2], dtype=int32)

In [93]:
arr

array([0, 1, 2, 3, 4, 5])

In [120]:
arr.reshape(6,1)

array([[0],
       [1],
       [2],
       [3],
       [4],
       [5]])

In [95]:
arr.reshape(4,3)

ValueError: cannot reshape array of size 6 into shape (4,3)

In [96]:
arr.reshape(6,1)

array([[0],
       [1],
       [2],
       [3],
       [4],
       [5]])

In [97]:
arr.reshape(1,6)

array([[0, 1, 2, 3, 4, 5]])

In [98]:
arr.max()

np.int64(5)

In [99]:
arr.min()

np.int64(0)

In [100]:
arr2

array([[ 3,  7,  4,  3,  3,  8,  5],
       [ 3,  5,  6,  6,  5,  6,  5],
       [ 5,  2,  8, 10,  5,  4,  4],
       [ 7,  7,  3,  7,  5,  3,  3],
       [ 8,  3,  3,  5,  5,  8,  2]], dtype=int32)

In [103]:
arr2[3:5,5:7]

array([[3, 3],
       [8, 2]], dtype=int32)

In [104]:
arr2[1]

array([3, 5, 6, 6, 5, 6, 5], dtype=int32)

In [107]:
arr2[1:3,2:4]

array([[ 6,  6],
       [ 8, 10]], dtype=int32)

In [109]:
arr2

array([[ 3,  7,  4,  3,  3,  8,  5],
       [ 3,  5,  6,  6,  5,  6,  5],
       [ 5,  2,  8, 10,  5,  4,  4],
       [ 7,  7,  3,  7,  5,  3,  3],
       [ 8,  3,  3,  5,  5,  8,  2]], dtype=int32)

In [113]:
arr2[:,4:6]

array([[3, 8],
       [5, 6],
       [5, 4],
       [5, 3],
       [5, 8]], dtype=int32)

In [114]:
arr2[:3,2:4]

array([[ 4,  3],
       [ 6,  6],
       [ 8, 10]], dtype=int32)

In [115]:
arr2[2:5,0:3]

array([[5, 2, 8],
       [7, 7, 3],
       [8, 3, 3]], dtype=int32)

In [ ]:
array([[ 3,  7,  4,  3,  3,  8,  5],
       [ 3,  5,  6,  6,  5,  6,  5],
       [ 5,  2,  8, 10,  5,  4,  4],
       [ 7,  7,  3,  7,  5,  3,  3],
       [ 8,  3,  3,  5,  5,  8,  2]], dtype=int32)


In [121]:
arr3=np.random.randint(2,9,(5,7))
print(arr3)

[[3 3 8 7 6 3 8]
 [2 6 3 4 8 8 2]
 [4 3 8 3 4 7 2]
 [7 5 6 3 7 2 4]
 [6 2 7 8 3 7 4]]


In [122]:
arr4=np.random.randint(9,15,(7,6))
print(arr4)

[[10 14 11 13 13 11]
 [10 12 12  9 11 13]
 [14  9 13  9 14 12]
 [13 12 13 10  9  9]
 [ 9 13  9 12 11 13]
 [12 14  9 10 10 10]
 [11 10 10 14 10  9]]
